### ISSUE TITLE
Is moving out of the home, the same as leaving?

### ISSUE THREAD

**Issue by CaroRob** [SuffolkLITLab/docassemble-MAMotiontoVacateMaritalHome#1]
@kateleebarry     This motion can ask the court to order the other party in your family law case to:

- Move out of your home.
- Stay away from your home.
- Move out of your home and stay away from your home.

Is this ok, or do we have to stick with 'leave' ?

**Comment by CaroRob** [comment]
Also can we include in this question 
the idea that you are asking the court for this order to protect, the health safety or welfare of you or your children - 
If this protection is a prerequisite for the motion, it makes sense to declare it as soon as possible.

**Comment by kateleebarry** [comment]
Move out’s fine

**Comment by kateleebarry** [comment]
> Also can we include in this question ...
> the idea that you are asking the court for this order to protect, the health safety or welfare of you or your children ?
> If this protection is a prerequisite for the motion, it makes sense to declare it as soon as possible.

I’m fine moving the order, there are just several pre-requisites. I tried sticking them all close to the beginning, but if you think this particular one should go earlier, I’m okay with that.
