### ISSUE TITLE
Suggestion if can't complete is to contact PFC, I think we should tell people to contact a lawyer / legal aid

### ISSUE THREAD

**Issue by CaroRob** [SuffolkLITLab/docassemble-MAMotiontoVacateMaritalHome#2]
Page id: add reasons cannot complete

On all kick out pages it says "Contact your Probate and Family Court if you still need to file a motion."

I think it should say, [Talk to a lawyer](https://MassLegalHelp.org/find-legal-aid) if you need help protecting your family from ${ opposing_party.name.first }

**Comment by CaroRob** [comment]
@kateleebarry @colarusso ?? As far as I know this is the only thing I think that is keeping us from launching? And it's not keeping us from launching, @nonprofittechy ?

**Comment by kateleebarry** [comment]
That's fine by me

**Comment by colarusso** [comment]
Edit made to incorporate above language.
